# Development Dockerfile
FROM node:22

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /usr/src/app

# Set the PNPM_HOME environment variable and update PATH
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

# Create the PNPM_HOME directory
RUN mkdir -p $PNPM_HOME/bin

# Set the SHELL environment variable
ENV SHELL=/bin/sh

# Copy pnpm lock file and package.json
COPY pnpm-lock.yaml ./
COPY package.json ./

# Install dependencies
RUN pnpm install

# Install nodemon globally
RUN pnpm add -g nodemon

# Copy the rest of the application source code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the application in development mode
CMD ["pnpm", "run", "start:dev"]
